---
lang: fr
output: 
  weasydoc::hpdf_document_base:
    engine: "weasyprint"
    css: "template_style.css"
    fig_caption: false
    keep_html: false
params:
  info:
    value:
      date: NA
      doc: "Facture"
      ndoc: "N0001"
      nclient: "C0001"
  config:
    value:
      name: "Company name<br/> Services"
      address1: "1 rue fictive"
      address2: "test"
      postal_code: "01000"
      city: "Testcity"
      mobile: "+33(0)6 00 00 00 00"
      e_mail: "contact@email.com"
      web: "www.siteweb.com"
      siret: "xxxxxxxxxxxxxxxxxx"
  logo: 
    value:
      yes: TRUE
      file: "logo_template.png"
      width: 35mm
  client:
    value:
      firstname: "firstname"
      name: "name"
      company: NA
      department: NA
      address1: "1 rue fictive"
      address2: "test"
      postal_code: "01000"
      city: "Testcity"
      mobile: "+33(0)6 00 00 00 00"
      e_mail: "contact@email.com"
  billing:
    value:
      company: NA
      department: NA
      siret: NA
      address1: "1 rue fictive"
      address2: "test"
      postal_code: "01000"
      city: "Testcity"
      mobile: "+33(0)6 00 00 00 00"
      e_mail: "contact@email.com"
  comment: "Some comments"
  services:
    value:
      data: NA
      totdata: NA
      tva: "no"
  bankinfo:
    value:
      holder: "HOLDER"
      bank: "Bank of fake"
      bic: "CCHAJUSAHXX"
      iban: "FR** **** **** **** **** **** ***"
  annexes:
    value:
      isannexes: "No"
      pathannexes: ""
---

```{r my_setup, include=FALSE}
options(knitr.kable.NA = '', message = FALSE)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
require(manageR)
```


<div class="wrapper">


---
#######################################
############# HEADER ##################
#######################################
---
<header>

<div class = "grid-container">

<div class = "row">

<div class = "col-5">
```{r echo = FALSE}
process_logo(params$logo)
```

:::{.big}
`r process_name(params$config$name)`
:::

<div class = "address">
```{r echo = FALSE, warning = FALSE}
process_config(params$config)
```
</div>

</div>


<div class = "col-7 centered">

<div class = "row">

:::{.boxheader}
`r process_boxheader(params$info, which = 1)`
:::

:::{.boxheader}
`r process_boxheader(params$info, which = 2)`
:::

:::{.boxheader}
`r process_boxheader(params$info, which = 3)`
:::

</div>

<div class = "row">

```{r echo = FALSE}
process_client(client = params$client, billing = params$billing, info = params$info)
```

</div>

</div>

</div>

</div>

</header>


---
#######################################
############### MAIN ##################
#######################################
---
<main>

<div class = "row topm">

```{r echo = FALSE}
process_comment(comment = params$comment, info = params$info)
```

</div>

<div class = "row services">

```{r echo = FALSE}
process_services(params$services)
```

</div>

<div class = "row total">

```{r echo = FALSE}
process_total(params$services, mode = params$info$doc)
```

:::{.foottable}
```{r echo = FALSE}
process_tva(params$services)
```
:::

</div>

</main>

---
#######################################
############# FOOTER ##################
#######################################
---
<footer>

```{r echo = FALSE}
process_bank(info = params$info, bankinfo = params$bankinfo, config = params$config)
```

</footer>
  
</div>



```{r echo = FALSE, eval = params$annexes$isannexes == "Yes"}
process_annexes(file = params$annexes$pathannexes)
```


